# Generated by Django 6.0.3 on 2026-04-03 13:35

import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default=4.45, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('short', 'Short Video (< 60s)'), ('long', 'Long Video')], default='short', max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=500, upload_to=frontend.models.PhotoUploadPath()),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=500, upload_to=frontend.models.VideoUploadPath()),
        ),
    ]
