# Generated by Django 5.2.12 on 2026-04-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_callsession_share_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='twilio_call_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='twilio_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='call_type',
            field=models.CharField(choices=[('browser', 'Browser to Browser (WebRTC)'), ('phone', 'Browser to Phone (PSTN)'), ('phone_to_phone', 'Phone to Phone')], default='browser', max_length=20),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_available_for_calls',
            field=models.BooleanField(default=False, help_text='Allow other users to call you'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='International format: +1234567890', max_length=20),
        ),
    ]
