# Generated by Django 5.2.12 on 2026-04-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
