# Generated by Django 6.0.4 on 2026-04-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_create_social_app'),
        ('frontend', '0015_alter_backgroundmedia_file_alter_feature_icon_image_and_more'),
    ]

    operations = [
    ]
